version: '3.5'

services:
  php-apache:
    image: diazdavid/dev-apache-php-7.4.3:latest
    container_name: php-sns-sqs-aws
    volumes:
      - ./:/var/www/html
      - ${AWS_DIRECTORY_PATH}:/root/.aws
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/apps/backend/public
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9014 remote_enable=1
    networks:
      - sns-sqs-aws

networks:
  sns-sqs-aws:
    name: sns-sqs-aws
